# Generated by Django 2.2.3 on 2019-10-05 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='farmer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GrainName', models.CharField(max_length=100)),
                ('GrainType', models.CharField(max_length=100)),
                ('GrainImage', models.ImageField(default='None', upload_to='images/')),
                ('GrainPrice', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Grain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grain_name', models.CharField(max_length=100)),
                ('grain_type', models.CharField(max_length=100)),
                ('grain_price', models.CharField(max_length=100)),
                ('grain_date', models.DateField(default='2019-10-05')),
                ('grain_image', models.ImageField(default='None', upload_to='images/')),
            ],
        ),
    ]
